name: engine_package_build

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main, ci ]
  repository_dispatch:
  workflow_dispatch:
  
jobs:
  build_engine_arm:
    name: 'Build and deploy engine for linux arm (32-bit).'

    runs-on: [self-hosted, linux]
       
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      
      - uses: actions/checkout@v1
      
      - name: Read stable engine version
        id: engine-version-stable
        run: echo ::set-output name=hash::$(cat engine.version.stable)
        
      - name: Test output
        run: echo ${{ steps.engine-version-stable.outputs.hash }}
      
      - name: build engine (armv7 hard-float debug)
        uses: ./.github/actions/build-engine
        with:
          ref: "${{ steps.engine-version-stable.outputs.hash  }}"
          is-host: false
          runtime-mode: debug
          os: linux
          cpu: arm
          additional-gn-args: '--embedder-for-target --disable-desktop-embeddings --no-build-glfw-shell --no-build-embedder-examples --no-goma'
          
      - name: build engine (armv7 hard-float profile)
        uses: ./.github/actions/build-engine
        with:
          ref: "${{ steps.engine-version-stable.outputs.hash  }}"
          is-host: false
          runtime-mode: profile
          os: linux
          cpu: arm
          additional-gn-args: '--embedder-for-target --disable-desktop-embeddings --no-build-glfw-shell --no-build-embedder-examples --no-goma'
      
      - name: build engine (armv7 hard-float release)
        uses: ./.github/actions/build-engine
        with:
          ref: "${{ steps.engine-version-stable.outputs.hash  }}"
          is-host: false
          runtime-mode: release
          os: linux
          cpu: arm
          additional-gn-args: '--embedder-for-target --disable-desktop-embeddings --no-build-glfw-shell --no-build-embedder-examples --no-goma'
