name: engine_package_build

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main, ci ]
  repository_dispatch:
  workflow_dispatch:
  
jobs:
  build_engine_arm:
    name: 'Build and deploy engine for linux arm (32-bit).'

    runs-on: [self-hosted, linux]
       
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      
      - name: Build & Configure engine
        uses: actions/build-engine@ci
        with:
          ref: ab46186b246f5a36bd1f3f295d14a43abb1e2f38
          is-host: false
          runtime-mode: debug
          os: linux
          cpu: arm

