name: engine_package_build

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main, ci ]
  repository_dispatch:
  workflow_dispatch:
  
jobs:
  pi4-debug:
    name: 'Build and deploy flutter engine for Raspberry Pi 4 (32-bit, debug mode).'

    runs-on: ubuntu-latest
       
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      
      - uses: actions/checkout@v1
      
      - name: Read stable engine version
        id: engine-version-stable
        run: echo ::set-output name=hash::$(cat engine.version.stable)
        
      - name: Test output
        run: echo ${{ steps.engine-version-stable.outputs.hash }}
      
      - name: build engine
        uses: ./.github/actions/build-engine
        with:
          ref: "${{ steps.engine-version-stable.outputs.hash  }}"
          is-host: false
          runtime-mode: debug
          os: linux
          cpu: arm
          additional-gn-args: '--embedder-for-target --disable-desktop-embeddings --no-build-glfw-shell --no-build-embedder-examples --no-goma'
    
  pi4-profile:
    name: 'Build and deploy flutter engine for Raspberry Pi 4 (32-bit, profile mode).'
    runs-on: ubuntu-latest
    steps:
      - name: Read stable engine version
        id: engine-version-stable
        run: echo ::set-output name=hash::$(cat engine.version.stable)
        
      - name: build engine
        uses: ./.github/actions/build-engine
        with:
          ref: "${{ steps.engine-version-stable.outputs.hash  }}"
          is-host: false
          runtime-mode: profile
          os: linux
          cpu: arm
          additional-gn-args: '--embedder-for-target --disable-desktop-embeddings --no-build-glfw-shell --no-build-embedder-examples --no-goma'
  
  pi4-release:
    name: 'Build and deploy flutter engine for Raspberry Pi 4 (32-bit, release mode).'
    runs-on: ubuntu-latest
    
    steps:
      - name: Read stable engine version
        id: engine-version-stable
        run: echo ::set-output name=hash::$(cat engine.version.stable)
        
      - name: build engine (armv7 hard-float release)
        uses: ./.github/actions/build-engine
        with:
          ref: "${{ steps.engine-version-stable.outputs.hash  }}"
          is-host: false
          runtime-mode: release
          os: linux
          cpu: arm
          additional-gn-args: '--embedder-for-target --disable-desktop-embeddings --no-build-glfw-shell --no-build-embedder-examples --no-goma'
