name: watch for flutter updates

on:
  # Check every 15 minutes
  schedule:    
    - cron: "*/15 * * * *"

  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

  workflow_dispatch:

jobs:
  check-for-roll:
    name: 'Check if stable engine commit changed'
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check-roll.outputs.changed }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ENGINE_ROLL_TOKEN }}
      
      # If we only want to find out the stable engine version, we can do `wget -O engine.version.stable https://raw.githubusercontent.com/flutter/flutter/stable/bin/internal/engine.version`
      # However we also want to find out the semver of the flutter release (3.0.5 for example),
      - uses: actions/checkout@v2
        with:
          repository: flutter/flutter
          ref: stable
          path: flutter
  
      - run: |
          cp flutter/bin/internal/engine.version engine.version.stable

      - name: Check if stable engine version changed 
        id: check-roll
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes"
            echo ::set-output name=changed::false
          else
            echo "Delta"
            echo ::set-output name=changed::true
          fi
      
      # reference: https://github.com/flutter/flutter/blob/a880c4ed3590477380c975f867406ba336834848/packages/flutter_tools/lib/src/version.dart#L703
      # if the flutter people ever decide to point more than one tags at the stable SDK commit we're in trouble here
      - name: find out flutter SDK semver for this engine version
        id: flutter-version
        working-directory: flutter
        run: |
          pwd
          git status
          git log -n 1
          git tag -l
          echo flutter version: $(git tag --points-at HEAD)
          echo ::set-output name=semver::$(git tag --points-at HEAD | tr -dc [:xdigit:])

      - name: Commit new stable engine version
        if: ${{ steps.check-roll.outputs.changed == 'true' }}
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Roll engine (stable)'
          add: 'engine.version.stable'
          tag: ${{ steps.flutter-version.outputs.semver }}
