name: watch for flutter updates

on:
  # Check every 15 minutes
  schedule:    
    - cron: "*/15 * * * *"

  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Get flutter engine.version for stable channel
        run: |
          wget -O engine.version.stable https://raw.githubusercontent.com/flutter/flutter/stable/bin/internal/engine.version
          ls -lah

      - name: Check if stable engine version changed 
        id: check-roll
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes"
            echo ::set-output name=changed::false
          else
            echo "Delta"
            echo ::set-output name=changed::true
          fi

      - name: Commit new stable engine version
        if: ${{ steps.check-roll.outputs.changed == 'true' }}
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Roll engine (stable)'
          add: 'engine.version.stable'
